### ISSUE TITLE
N卡的烦恼

### ISSUE THREAD

**Issue by StarYunmeng** [yhl452493373/ASROCK-X570-Taichi-Radeon-VII#1]
我用的是最糟糕的X570太极+R5 3600+1050Ti(N卡头疼)内存8GX2,这个可以用吗?

**Comment by yhl452493373** [comment]
> 我用的是最糟糕的X570太极+R5 3600+1050Ti(N卡头疼)内存8GX2,这个可以用吗?

换A卡。。
